### ISSUE TITLE
哥们请问你的Skia版本是多少？

### ISSUE THREAD

**Issue by l1shu** [NeoPocketCat/AtomGraphics#1]
我尝试自己编译了 Skia 但是生成的 .a 文件无法在工程中正确使用，报错：pngget.c: error:undefined symbol to ‘atof’

找到你的 github 拿下来之后发现可以跑起来，但是Skia 版本貌似有点旧，想问下你的 Skia 版本是多少？

**Comment by Polepoint** [comment]
> 我尝试自己编译了 Skia 但是生成的 .a 文件无法在工程中正确使用，报错：pngget.c: error:undefined symbol to ‘atof’
> 
> 找到你的 github 拿下来之后发现可以跑起来，但是Skia 版本貌似有点旧，想问下你的 Skia 版本是多少？

https://github.com/Polepoint/AtomGraphics/blob/master/AtomGraphics/third_party/skia/version.json
